import { Opportunity } from './types';

export const SEED_COURSES: Opportunity[] = [
  {
    "id": "AAMmof7653k",
    "name": "American Math Competition",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "3",
    "description": "A prestigious international mathematics competition hosted by the Mathematical Association of America, challenging students with rigorous problem-solving.",
    "image": "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=600&auto=format&fit=crop",
    "enrolled": 12,
    "capacity": 50
  },
  {
    "id": "HSPmof7653k",
    "name": "HSP Academic Mentoring",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "4",
    "description": "A specialised mentoring programme under the Humanities Scholarship Programme (HSP), providing deep academic guidance and research support.",
    "image": "https://images.unsplash.com/photo-1513258496099-48168024adb0?q=80&w=600&auto=format&fit=crop",
    "enrolled": 5,
    "capacity": 15
  },
  {
    "id": "TDPmof7653k",
    "name": "TDP Learning Journey",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "5",
    "description": "An immersive off-campus learning experience designed for TDP students to explore industry applications and higher education pathways.",
    "image": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=600&auto=format&fit=crop",
    "enrolled": 20,
    "capacity": 40
  },
  {
    "id": "OGLmof7653k",
    "name": "Orientation Group Leaders",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 1",
    "week": "6",
    "description": "Leadership role facilitating the integration of new JC1 students into the school community through activities and mentorship.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 45,
    "capacity": 60
  },
  {
    "id": "CNYmof7653k",
    "name": "Chinese New Year Organising Committee",
    "domain": "Aesthetics & Culture",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "7",
    "description": "A student-led committee responsible for planning and executing the annual Chinese New Year celebrations, showcasing cultural heritage.",
    "image": "https://images.unsplash.com/photo-1563812845341-3b707e7b686b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 25
  },
  {
    "id": "NUMmof7653k",
    "name": "NUS Learning Journey (Math)",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "9",
    "description": "An introductory visit to the NUS Mathematics Department, featuring academic talks and exposure to university-level mathematics.",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 35,
    "capacity": 80
  },
  {
    "id": "PMWmof7653k",
    "name": "Precision medicine workshop at Science Centre",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Hands-on workshop exploring the future of healthcare through genomics and personalised medical treatments.",
    "image": "https://images.unsplash.com/photo-1579154235602-3c35bd799335?q=80&w=600&auto=format&fit=crop",
    "enrolled": 22,
    "capacity": 30
  },
  {
    "id": "SSFmof7653k",
    "name": "Learning Journey to SSEF",
    "domain": "STEM & Innovation",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Educational visit to the Singapore Science and Engineering Fair, allowing students to observe top-tier research projects.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 18,
    "capacity": 40
  },
  {
    "id": "CPDmof7653k",
    "name": "CPDD MOI Pitch and Project Showcase",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "A platform for students to pitch innovative projects and showcase their Mode of Inquiry (MOI) findings to national curriculum developers.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 8,
    "capacity": 20
  },
  {
    "id": "NGDmof7653k",
    "name": "NUS Geog Department Open House (Feb)",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "as per calendar",
    "description": "Introductory open house session for students interested in Geography and environmental studies at the university level.",
    "image": "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 12,
    "capacity": 100
  },
  {
    "id": "IMCmof7653k",
    "name": "International Mathematics Modelling Competition (IMMC)",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "1",
    "description": "Global competition challenging students to use mathematical modelling to solve complex real-world problems.",
    "image": "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=600&auto=format&fit=crop",
    "enrolled": 6,
    "capacity": 20
  },
  {
    "id": "LKCAmof7653k",
    "name": "LKC Anatomy Challenge",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "4",
    "description": "Highly competitive anatomy competition hosted by the Lee Kong Chian School of Medicine for aspiring medical students.",
    "image": "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=600&auto=format&fit=crop",
    "enrolled": 4,
    "capacity": 10
  },
  {
    "id": "CSWmof7653k",
    "name": "CareersSAdvance Work Immersion - Career Mentoring",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "9",
    "description": "Structured work immersion programme providing students with professional mentorship and real-world workplace exposure.",
    "image": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=600&auto=format&fit=crop",
    "enrolled": 25,
    "capacity": 50
  },
  {
    "id": "SLCmof7653k",
    "name": "Servant Leaders' Convention (Presenters)",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "10",
    "description": "Presentation opportunity for student leaders to share their service-learning initiatives and leadership growth.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 10,
    "capacity": 30
  },
  {
    "id": "NCGmof7653k",
    "name": "Singapore National Crystal Growing Challenge",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "Scientific challenge focused on the precision growth and analysis of high-quality crystals, combining chemistry and craft.",
    "image": "https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=600&auto=format&fit=crop",
    "enrolled": 6,
    "capacity": 20
  },
  {
    "id": "CHXmof7653k",
    "name": "ChrySAlis Exco",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "Executive committee leadership role for the ChrySAlis programme, overseeing core school events and initiatives.",
    "image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=600&auto=format&fit=crop",
    "enrolled": 12,
    "capacity": 15
  },
  {
    "id": "CHMmof7653k",
    "name": "ChrySAlis Mentors/Facilitators",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "Mentorship role for students to guide junior levels through the ChrySAlis personal development curriculum.",
    "image": "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 20,
    "capacity": 30
  },
  {
    "id": "MHWmof7653k",
    "name": "Mental Health and Wellbeing Assembly Student Facilitators",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "2",
    "description": "Student-led peer support initiative to facilitate assembly sessions on mental wellness and resilience.",
    "image": "https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 40
  },
  {
    "id": "PSDmof7653k",
    "name": "Public Service Dialogue",
    "domain": "Global Awareness",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "as per calendar",
    "description": "Interactive dialogue session with public service leaders to discuss policy, governance, and civic responsibility.",
    "image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=600&auto=format&fit=crop",
    "enrolled": 30,
    "capacity": 100
  },
  {
    "id": "FASmof7653k",
    "name": "Farewell Assembly Student Organising Committee",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 4",
    "week": "4",
    "description": "Planning and execution of the final assembly for graduating students, including performances and tributes.",
    "image": "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 25
  },
  {
    "id": "LRXmof7653k",
    "name": "Student Leaders Retreat Exco",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 4",
    "week": "10",
    "description": "High-level planning role for the annual student leadership retreat, focusing on vision and team cohesion.",
    "image": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=600&auto=format&fit=crop",
    "enrolled": 8,
    "capacity": 12
  },
  {
    "id": "LUFmof7653k",
    "name": "Local University Forum - Faculty Talks",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 4",
    "week": "as per calendar",
    "description": "In-depth talks from various local university faculties providing detailed insights into specific majors and careers.",
    "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 40,
    "capacity": 200
  },
  {
    "id": "ALWmof7653l",
    "name": "Art x Lit Workshop",
    "domain": "Aesthetics & Culture",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "1",
    "description": "Creative workshop exploring the intersection of visual arts and literary themes.",
    "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 30
  },
  {
    "id": "STICmof7653l",
    "name": "Shanghai Texas Instrument Cup",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "1",
    "description": "Introduction to graphing calculator technology and basic competitive problem-solving.",
    "image": "https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?q=80&w=600&auto=format&fit=crop",
    "enrolled": 10,
    "capacity": 50
  },
  {
    "id": "SBLmof7653l",
    "name": "Singapore Biology League Competition",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "2",
    "description": "Advanced national competition for biology enthusiasts covering genetics, ecology, and biochemistry.",
    "image": "https://images.unsplash.com/photo-1532187875605-2fe358a71428?q=80&w=600&auto=format&fit=crop",
    "enrolled": 8,
    "capacity": 20
  },
  {
    "id": "ILSmmof7653l",
    "name": "Inter-JC Literature Symposium",
    "domain": "Aesthetics & Culture",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "4",
    "description": "A collaborative gathering of literature students from various JCs to discuss contemporary literary trends.",
    "image": "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?q=80&w=600&auto=format&fit=crop",
    "enrolled": 20,
    "capacity": 60
  },
  {
    "id": "SCCmof7653l",
    "name": "Sports Carnival (Sports)",
    "domain": "Physical & Sports",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "6",
    "description": "Annual school-wide athletic event promoting physical fitness and house spirit.",
    "image": "https://images.unsplash.com/photo-1502945015378-0e284ca1c5be?q=80&w=600&auto=format&fit=crop",
    "enrolled": 100,
    "capacity": 500
  },
  {
    "id": "ESCmof7653l",
    "name": "SA Encore Student Organising Committee",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 4",
    "week": "as per calendar",
    "description": "Student committee planning the school's signature talent showcase and performing arts event.",
    "image": "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 30
  },
  {
    "id": "PSWmof7653l",
    "name": "ECG Electives - Professional Skills",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Any",
    "week": "as per calendar",
    "description": "Series of workshops on resume building, interview techniques, and professional networking.",
    "image": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=600&auto=format&fit=crop",
    "enrolled": 20,
    "capacity": 100
  },
  {
    "id": "OUTmof7653l",
    "name": "Overseas University Talks (UK, US etc)",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Any",
    "week": "as per calendar",
    "description": "Information sessions featuring representatives from top overseas universities regarding admissions and scholarships.",
    "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 25,
    "capacity": 150
  },
  {
    "id": "H3Pmof7653l",
    "name": "H3 programme (Internal & External)",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "1",
    "description": "Advanced academic curriculum for high-achieving JC2 students, offering specialized knowledge in chosen subjects.",
    "image": "https://images.unsplash.com/photo-1513258496099-48168024adb0?q=80&w=600&auto=format&fit=crop",
    "enrolled": 40,
    "capacity": 100
  },
  {
    "id": "OHFmof7653l",
    "name": "Open House Student Facilitators",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 1",
    "week": "2",
    "description": "Guiding prospective students and parents through the school and sharing student life experiences.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 50,
    "capacity": 80
  },
  {
    "id": "EPBmof7653l",
    "name": "ECG ePortfolio Building Workshops - Tech Set Up",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "Guidance on using digital platforms to build and maintain an effective ECG ePortfolio.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 200
  },
  {
    "id": "YTBCmof7653l",
    "name": "Young Trailblazer Competition",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "National innovation competition for students to develop social enterprise or technical solutions to community issues.",
    "image": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=600&auto=format&fit=crop",
    "enrolled": 10,
    "capacity": 30
  },
  {
    "id": "SISPmof7653l",
    "name": "Scientists-in-Schools Programme",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "Any",
    "description": "Long-term scientific research programme pairing students with industry or academic scientists for mentorship.",
    "image": "https://images.unsplash.com/photo-1532187875605-2fe358a71428?q=80&w=600&auto=format&fit=crop",
    "enrolled": 5,
    "capacity": 15
  },
  {
    "id": "KSAmof7653m",
    "name": "CareersSAdvance Work Immersion (March)",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Intensive one-week work immersion programme during the March holidays for practical career exploration.",
    "image": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=600&auto=format&fit=crop",
    "enrolled": 20,
    "capacity": 40
  },
  {
    "id": "GBAmof7653m",
    "name": "Global Awareness Fortnight (March)",
    "domain": "Global Awareness",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Two-week programme featuring international speakers and cultural workshops to broaden students' global perspectives.",
    "image": "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 50,
    "capacity": 500
  },
  {
    "id": "SADmof7653m",
    "name": "SA Saints Dialogue (March)",
    "domain": "Leadership & Service",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Dialogue session featuring prominent alumni sharing their leadership journeys and life after SAJC.",
    "image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=600&auto=format&fit=crop",
    "enrolled": 30,
    "capacity": 200
  },
  {
    "id": "SMLmof7653m",
    "name": "Saints Music & Literature Festival (March)",
    "domain": "Aesthetics & Culture",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "A week-long celebration of student creativity through performances, readings, and collaborative workshops.",
    "image": "https://images.unsplash.com/photo-1514320298324-a4a27858ad32?q=80&w=600&auto=format&fit=crop",
    "enrolled": 40,
    "capacity": 300
  },
  {
    "id": "SAWmof7653m",
    "name": "SA Wellness Fortnight (March)",
    "domain": "Leadership & Service",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Holistic programme focused on physical and mental well-being, featuring yoga, mindfulness, and fitness sessions.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 60,
    "capacity": 400
  },
  {
    "id": "SWAmof7653m",
    "name": "Saints Wings Awards / SLC (March)",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Annual awards ceremony recognizing outstanding student contributions in leadership and community service.",
    "image": "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 50
  },
  {
    "id": "ECLmof7653m",
    "name": "ECG Learning Journey (March)",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Off-campus visits to various universities and professional institutions to understand career landscapes.",
    "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 40,
    "capacity": 120
  },
  {
    "id": "LSLmof7653m",
    "name": "Local Service Learning (March)",
    "domain": "Leadership & Service",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 1",
    "week": "10",
    "description": "Organized community service activities with local partners during the mid-term break.",
    "image": "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 80,
    "capacity": 200
  },
  {
    "id": "OSSmof7653m",
    "name": "Overseas Service Learning (June/Dec)",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Holiday",
    "week": "Holidays",
    "description": "International service-learning expeditions focusing on sustainable community development projects.",
    "image": "https://images.unsplash.com/photo-1469571483333-f33f6173bc3e?q=80&w=600&auto=format&fit=crop",
    "enrolled": 12,
    "capacity": 20
  },
  {
    "id": "CMAmof7653m",
    "name": "Chinese MAJU Learning Journey",
    "domain": "Mother Tongue",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "1",
    "description": "Cultural and language immersion programme for Chinese Language students through experiential learning.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 30
  },
  {
    "id": "MMAmof7653m",
    "name": "Malay MAJU Learning Journey",
    "domain": "Mother Tongue",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "1",
    "description": "Cultural and language immersion programme for Malay Language students through experiential learning.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop",
    "enrolled": 12,
    "capacity": 25
  },
  {
    "id": "TMAmof7653m",
    "name": "Tamil MAJU Learning Journey",
    "domain": "Mother Tongue",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "1",
    "description": "Cultural and language immersion programme for Tamil Language students through experiential learning.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop",
    "enrolled": 10,
    "capacity": 20
  },
  {
    "id": "NCAmof7653m",
    "name": "Non-CL/ML/TL Mother Tongue MAJU Learning Journey",
    "domain": "Mother Tongue",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "1",
    "description": "Language enrichment for students taking non-standard mother tongues or other languages.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop",
    "enrolled": 8,
    "capacity": 20
  },
  {
    "id": "WSHmof7653m",
    "name": "Work Shadowing Programme (June/Nov)",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Holiday",
    "week": "Holidays",
    "description": "Opportunity to shadow industry professionals to gain first-hand insights into specific career fields.",
    "image": "https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=600&auto=format&fit=crop",
    "enrolled": 15,
    "capacity": 40
  },
  {
    "id": "TUCmof7653m",
    "name": "TDP University & Career Fair (T2W10)",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "10",
    "description": "Large-scale fair featuring university representatives and career consultants for all students.",
    "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
    "enrolled": 100,
    "capacity": 1000
  },
  {
    "id": "zNlmof7653m",
    "name": "Singapore International STEM Innovation Challenge (SISTEMIC)",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "10",
    "description": "An international STEM innovation challenge pushing students to develop creative solutions to real-world problems through science, technology, engineering, and mathematics.",
    "image": "https://images.unsplash.com/photo-1571260899304-4250701120f6?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "mUXmof7653n",
    "name": "MAJU",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "10",
    "description": "A distinguished enrichment programme (MAJU) designed to stretch students' potential through curated academic and experiential learning opportunities.",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "7Ijmof7653n",
    "name": "ECG ePortfolio Building Workshops - Tech Set Up",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "A practical workshop guiding students through the technical setup of their ECG ePortfolio — a digital showcase of their career exploration and personal development journey.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "Pewmof7653n",
    "name": "Young Trailblazer Competition",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "An innovation competition for young trailblazers who dare to think differently, challenging students to propose bold solutions to pressing societal challenges.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "IL8mof7653n",
    "name": "Scientists-in-Schools Programme",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 2",
    "week": "",
    "description": "A unique programme connecting students with practising scientists in schools, offering mentorship, exposure to real research, and inspiration for future STEM careers.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "nkamof7653n",
    "name": "Art x Lit Workshop",
    "domain": "Aesthetics & Culture",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "1",
    "description": "A creative interdisciplinary workshop blending visual art with literature, encouraging students to explore storytelling and expression through multiple artistic lenses.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "2sbmof7653n",
    "name": "Shanghai Texas Instrument Cup",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "1",
    "description": "An international mathematics competition from Shanghai featuring Texas Instruments, challenging students with creative problem-solving using graphing calculator technology.",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "YtJmof7653n",
    "name": "Singapore Biology League Competition",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "2",
    "description": "A national biology league competition testing students' knowledge and analytical skills across the breadth of biological sciences in a competitive team format.",
    "image": "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "APDmof7653n",
    "name": "Inter-JC Literature Symposium",
    "domain": "Aesthetics & Culture",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "4",
    "description": "A collaborative inter-JC symposium bringing literature students together to discuss, debate, and celebrate literary works, themes, and critical perspectives.",
    "image": "https://images.unsplash.com/photo-1571260899304-4250701120f6?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "13wmof7653n",
    "name": "Sports Carnival (Sports)",
    "domain": "Physical & Sports",
    "tier": 1,
    "level": "JC1 & JC2",
    "term": "Term 3",
    "week": "6",
    "description": "A spirited school-wide sports carnival featuring a variety of athletic events and team games, building camaraderie, school spirit, and healthy competition.",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "IVVmof7653n",
    "name": "SA Encore Student Organising Committee",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "Term 4",
    "week": "as per calendar",
    "description": "A student organising committee responsible for curating and executing SA Encore — a memorable school event celebrating student talents and achievements.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "c2jmof7653n",
    "name": "ECG Electives - Professional Skills",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "",
    "week": "as per calendar",
    "description": "A series of elective workshops focused on building professional skills such as resume writing, interview techniques, and workplace readiness for future careers.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "z8jmof7653n",
    "name": "Overseas University Talks (UK, US etc)",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC1 & JC2",
    "term": "",
    "week": "as per calendar",
    "description": "Informative sessions featuring representatives from overseas universities (UK, US, and beyond), helping students explore international higher education pathways.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "6lQmof7653n",
    "name": "H3 programme (Internal & External)",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "1",
    "description": "An advanced academic programme (H3 level) offering both internally taught and externally examined modules for students seeking intellectual depth beyond the standard curriculum.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "zqZmof7653n",
    "name": "Open House Student Facilitators",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 1",
    "week": "2",
    "description": "A student facilitator role during Open House, where student leaders guide prospective students and parents through the school, showcasing SAJC's vibrant community.",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "IcEmof7653n",
    "name": "TDP Learning Journey",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "4",
    "description": "A curated learning journey under the Talent Development Programme, providing students with exposure to industries, institutions, and ideas that inspire future pursuits.",
    "image": "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "HDPmof7653n",
    "name": "Orientation Group Leaders",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 1",
    "week": "5",
    "description": "A pivotal leadership role where Orientation Group Leaders welcome and mentor new students, setting the tone for a warm and inclusive school culture.",
    "image": "https://images.unsplash.com/photo-1571260899304-4250701120f6?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "9ZXmof7653n",
    "name": "Chinese New Year Organising Committee",
    "domain": "Aesthetics & Culture",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "7",
    "description": "A student committee responsible for planning and executing the school's Chinese New Year celebrations, blending cultural traditions with creative event management.",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "hPkmof7653n",
    "name": "NUS Learning Journey (Math)",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC2",
    "term": "Term 1",
    "week": "9",
    "description": "A mathematical learning journey to NUS, exposing students to university-level mathematics, research, and the real-world applications of mathematical thinking.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "3GHmof7653n",
    "name": "Precision medicine workshop at Science Centre",
    "domain": "STEM & Innovation",
    "tier": 1,
    "level": "JC2",
    "term": "Term 1",
    "week": "10",
    "description": "A specialised workshop at the Science Centre exploring the cutting-edge field of precision medicine, connecting classroom biology to future healthcare innovations.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "DWWmof7653n",
    "name": "Learning Journey to SSEF",
    "domain": "STEM & Innovation",
    "tier": 2,
    "level": "JC2",
    "term": "Term 1",
    "week": "10",
    "description": "A learning journey to the Singapore Science and Engineering Fair (SSEF), exposing students to outstanding student research projects and inspiring scientific inquiry.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "1cwmof7653n",
    "name": "CPDD MOI Pitch and Project Showcase",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "10",
    "description": "A national showcase organised by CPDD where students pitch MOI (Modes of Inquiry) projects, demonstrating creativity, critical thinking, and effective communication.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "33bmof7653n",
    "name": "NUS Geog Department Open House (Feb)",
    "domain": "Cognitive & Academic",
    "tier": 1,
    "level": "JC2",
    "term": "Term 1",
    "week": "as per calendar",
    "description": "An open house visit to NUS Geography Department, giving students a preview of university-level geographical studies, research opportunities, and career pathways.",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "unzmof7653n",
    "name": "HSP Academic Mentoring",
    "domain": "Cognitive & Academic",
    "tier": 3,
    "level": "JC2",
    "term": "Term 1",
    "week": "",
    "description": "A personalised mentoring programme under the Humanities Scholarship Programme, pairing students with academic mentors for sustained intellectual growth and scholarly development.",
    "image": "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "DsXmof7653n",
    "name": "International Mathematics Modelling Competition (IMMC)",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC2",
    "term": "Term 2",
    "week": "1",
    "description": "An international competition challenging students to apply mathematical modelling techniques to solve complex, open-ended real-world problems as a team.",
    "image": "https://images.unsplash.com/photo-1571260899304-4250701120f6?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "f1Gmof7653n",
    "name": "LKC Anatomy Challenge",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC2",
    "term": "Term 2",
    "week": "4",
    "description": "A rigorous anatomy challenge organised by LKC School of Medicine, testing students' knowledge of human anatomy and their aptitude for the medical sciences.",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "SCRmof7653n",
    "name": "CareersSAdvance Work Immersion - Career Mentoring",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC2",
    "term": "Term 2",
    "week": "9",
    "description": "An immersive career mentoring programme connecting students with industry professionals for sustained guidance, workplace exposure, and career clarity.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "Q7dmof7653n",
    "name": "Servant Leaders' Convention (Presenters)",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 2",
    "week": "10",
    "description": "A convention where student leaders present their servant leadership journeys and projects, sharing insights and inspiring peers through storytelling and reflection.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "6aamof7653n",
    "name": "Singapore National Crystal Growing Challenge",
    "domain": "STEM & Innovation",
    "tier": 3,
    "level": "JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "A hands-on national competition where students grow crystals, applying chemistry knowledge to achieve the largest and most perfect crystal structures.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "1DCmof7653n",
    "name": "ChrySAlis Exco",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "An executive leadership role within the ChrySAlis programme, where Exco members drive the planning, coordination, and vision of this signature leadership initiative.",
    "image": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "rw8mof7653n",
    "name": "ChrySAlis Mentors/Facilitators",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC2",
    "term": "Term 2",
    "week": "as per calendar",
    "description": "A mentoring and facilitation role within ChrySAlis, where experienced students guide and support participants through leadership development activities and reflections.",
    "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "S1Amof7653n",
    "name": "Mental Health and Wellbeing Assembly Student Facilitators",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 3",
    "week": "2",
    "description": "A student facilitation role during the Mental Health and Wellbeing Assembly, leading peers through meaningful conversations and activities that promote emotional wellness.",
    "image": "https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "Updmof7653n",
    "name": "Public Service Dialogue",
    "domain": "Global Awareness",
    "tier": 2,
    "level": "JC2",
    "term": "Term 3",
    "week": "",
    "description": "A dialogue session connecting students with public service leaders, offering insights into governance, policy-making, and opportunities to serve Singapore.",
    "image": "https://images.unsplash.com/photo-1571260899304-4250701120f6?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "Ggzmof7653n",
    "name": "Farewell Assembly Student Organising Committee",
    "domain": "Leadership & Service",
    "tier": 2,
    "level": "JC2",
    "term": "Term 4",
    "week": "4",
    "description": "A student organising committee entrusted with planning a heartfelt Farewell Assembly, creating a memorable send-off that celebrates the graduating cohort's journey.",
    "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "sQjmof7653n",
    "name": "Student Leaders Retreat Exco",
    "domain": "Leadership & Service",
    "tier": 3,
    "level": "JC2",
    "term": "Term 4",
    "week": "10",
    "description": "An executive leadership role in planning and running the Student Leaders Retreat, shaping the programme that develops the next generation of school leaders.",
    "image": "https://images.unsplash.com/photo-1531545514251-b159ce8bf590?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  },
  {
    "id": "yfPmof7653n",
    "name": "Local University Forum - Faculty Talks",
    "domain": "Cognitive & Academic",
    "tier": 2,
    "level": "JC2",
    "term": "",
    "week": "as per calendar",
    "description": "A forum featuring faculty talks from local universities, giving students direct access to academic insights, course information, and admissions guidance.",
    "image": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop",
    "enrolled": 0
  }
];
